version: "3.4"
services:
  edge-novnc:
    image: itsalljustdata/edge-novnc
    container_name: edge-novnc
    hostname: edge-novnc
    volumes: 
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      # Make sure you 'touch ./vnc.log' first, otherwise docker will create a folder!
      # - ./vnc.log:'/home/iajd/.vnc/edge-novnc:1.log'
    ports: 
      - 6080:6080/tcp
    environment:
      TZ: Australia/Perth
      #
      # Default Values
      #
      # VNC_PASSWD: password
      # WIDTH: 1600
      # HEIGHT: 900
      # PUID: 1000
      # PGID: 1000
      # LANGUAGE: en_AU.UTF8
      # TZ: Etc/UTC
